[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-additive-widgets"
version = "0.1.dev0"
description = "Visualization toolkit for parametric additive simulations "
readme = "README.rst"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.core@ansys.com"},
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "importlib-metadata >=4.0",
    "ansys-additive-core >=0.17"
]

[project.optional-dependencies]
tests = [
    "pytest==7.4.3",
    "pytest-cov==4.1.0",
]
doc = [
    "ansys-sphinx-theme==0.12.5",
    "numpydoc==1.6.0",
    "sphinx==7.2.6",
    "sphinx-copybutton==0.5.2",
]


[tool.flit.module]
name = "ansys.additive.widgets"

[project.urls]
Source = "https://github.com/ansys/pyadditive-widgets"
Tracker = "https://github.com/ansys/pyadditive-widgets/issues"
Homepage = "https://github.com/ansys/pyadditive-widgets"


[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests"]

[tool.coverage.run]
source = ["ansys.additive"]

[tool.coverage.report]
show_missing = true
